/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uclv.crash.gui;

import com.uclv.crash.gui.utils.ActionDelegate;
import com.uclv.crash.gui.social.*;
import com.uclv.crash.gui.utils.*;
import com.uclv.crash.gui.partials.*;
import java.util.Stack;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Yasiel Cabrera
 */
public final class App extends javax.swing.JFrame {

    /**
     * referencia to this frame
     */
    public static App REFERENCE;

    /**
     * Creates new form App
     */
    @SuppressWarnings("LeakingThisInConstructor")
    public App() {
        setUndecorated(true);
        initComponents();
        this.setIconImage((new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Graduate_100px.png"))).getImage());
        App.REFERENCE = this;
        //create settings...
        Settings settings = new Settings();
        settings.load();
        settings.apply();
        AppStorage.setSettings(settings);
        //end settings
        AppEvents.initializeEvents();//adiciona todos los eventos de los componentes de la App
        MoveManager.offset = toolBarPanel.getWidth();
        MoveManager.setAppMoveListener(title, this);
        setLocationRelativeTo(null);

        AppActions.showHome();//para que muestre inicialmente el panel de las ER
        
        
        //no implemented yet
        saveBttn.setVisible(false);
        saveIndicator.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        full = new javax.swing.JPanel();
        toolBarPanel = new javax.swing.JPanel();
        helpBttn = new javax.swing.JLabel();
        helpIndicator = new javax.swing.JLabel();
        settingsBttn = new javax.swing.JLabel();
        settingsIndicator = new javax.swing.JLabel();
        workspaceBttn = new javax.swing.JLabel();
        workspaceIndicator = new javax.swing.JLabel();
        saveBttn = new javax.swing.JLabel();
        saveIndicator = new javax.swing.JLabel();
        newIndicator = new javax.swing.JLabel();
        newBttn = new javax.swing.JLabel();
        logoBttn = new javax.swing.JLabel();
        homeBttn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        full.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        toolBarPanel.setBackground(new java.awt.Color(0, 0, 51));
        toolBarPanel.setMaximumSize(new java.awt.Dimension(70, 32767));
        toolBarPanel.setMinimumSize(new java.awt.Dimension(50, 0));
        toolBarPanel.setPreferredSize(new java.awt.Dimension(50, 0));

        helpBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Help_34px.png"))); // NOI18N
        helpBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        helpIndicator.setBackground(new java.awt.Color(0, 102, 153));
        helpIndicator.setOpaque(true);

        settingsBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Settings_34px.png"))); // NOI18N
        settingsBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        settingsIndicator.setBackground(new java.awt.Color(0, 102, 153));
        settingsIndicator.setOpaque(true);

        workspaceBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Mind_Map_34px.png"))); // NOI18N
        workspaceBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        workspaceIndicator.setBackground(new java.awt.Color(0, 102, 153));
        workspaceIndicator.setOpaque(true);

        saveBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Save_34px.png"))); // NOI18N
        saveBttn.setToolTipText("Guardar");
        saveBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        saveIndicator.setBackground(new java.awt.Color(0, 102, 153));
        saveIndicator.setOpaque(true);

        newIndicator.setBackground(new java.awt.Color(0, 102, 153));
        newIndicator.setOpaque(true);

        newBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Add_Property_34px.png"))); // NOI18N
        newBttn.setToolTipText("Nuevo");
        newBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        logoBttn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Graduate_34px.png"))); // NOI18N
        logoBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoBttnMouseClicked(evt);
            }
        });

        homeBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Home_34px.png"))); // NOI18N
        homeBttn.setToolTipText("Inicio");
        homeBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        homeIndicator.setBackground(new java.awt.Color(0, 102, 153));
        homeIndicator.setOpaque(true);

        javax.swing.GroupLayout toolBarPanelLayout = new javax.swing.GroupLayout(toolBarPanel);
        toolBarPanel.setLayout(toolBarPanelLayout);
        toolBarPanelLayout.setHorizontalGroup(
            toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toolBarPanelLayout.createSequentialGroup()
                        .addComponent(helpBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helpIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolBarPanelLayout.createSequentialGroup()
                        .addComponent(settingsBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(settingsIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolBarPanelLayout.createSequentialGroup()
                        .addComponent(workspaceBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(workspaceIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolBarPanelLayout.createSequentialGroup()
                        .addComponent(saveBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolBarPanelLayout.createSequentialGroup()
                        .addComponent(newBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolBarPanelLayout.createSequentialGroup()
                        .addComponent(homeBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(logoBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        toolBarPanelLayout.setVerticalGroup(
            toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeIndicator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newIndicator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveIndicator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workspaceBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workspaceIndicator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsIndicator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(toolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpIndicator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setPreferredSize(new java.awt.Dimension(876, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Delete_24px.png"))); // NOI18N
        jLabel1.setToolTipText("Cerrar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_GitHub_35px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Facebook_35px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Twitter_35px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Google_Plus_35px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Subtract_24px.png"))); // NOI18N
        jLabel10.setToolTipText("Minimizar");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("REAT");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addGap(102, 102, 102)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout coverLayout = new javax.swing.GroupLayout(cover);
        cover.setLayout(coverLayout);
        coverLayout.setHorizontalGroup(
            coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        coverLayout.setVerticalGroup(
            coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
            .addComponent(cover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fullLayout = new javax.swing.GroupLayout(full);
        full.setLayout(fullLayout);
        fullLayout.setHorizontalGroup(
            fullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullLayout.createSequentialGroup()
                .addComponent(toolBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fullLayout.setVerticalGroup(
            fullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toolBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(full, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(full, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setExtendedState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void logoBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoBttnMouseClicked
        executeBackAction();
    }//GEN-LAST:event_logoBttnMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if (activeSection != App.GITHUB_SECTION) {
            activeSection = App.GITHUB_SECTION;
            clearIndicators();
            LayoutUtils.setPanelInto(cover, new Git());
            deactivateBackArrow();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (activeSection != App.FACEBOOK_SECTION) {
            activeSection = App.FACEBOOK_SECTION;
            clearIndicators();
            LayoutUtils.setPanelInto(cover, new Facebook());
            deactivateBackArrow();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if (activeSection != App.TWITTER_SECTION) {
            activeSection = App.TWITTER_SECTION;
            clearIndicators();
            LayoutUtils.setPanelInto(cover, new Twitter());
            deactivateBackArrow();
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if (activeSection != App.GOOGLE_SECTION) {
            activeSection = App.GOOGLE_SECTION;
            clearIndicators();
            LayoutUtils.setPanelInto(cover, new Google());
            deactivateBackArrow();
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    public void clearIndicators() {
        homeIndicator.setVisible(false);
        newIndicator.setVisible(false);
        saveIndicator.setVisible(false);
        workspaceIndicator.setVisible(false);
        settingsIndicator.setVisible(false);
        helpIndicator.setVisible(false);
    }

    /**
     * cambia el panel del cover (workspace)
     *
     * @param panel
     */
    public void changeCover(JPanel panel) {
        LayoutUtils.setPanelInto(cover, panel);
    }

    private final ImageIcon logo = new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Graduate_34px.png"));
    private final ImageIcon backArrow = new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Chevron_Left_34px.png"));
    /**
     * True si la flecha esta activa, false en caso contrario
     */
    private boolean backActivate = false;
    /**
     * Se ejecuta la ultima accion que esta en la lista cuando se pulse el boton
     * de atras. Esta lista debera estar vacia si backActivate es false
     */
    private Stack<ActionDelegate> backAction = new Stack<>();

    /**
     * Activa el boton de regresar.
     *
     * @param action Accion que se ejecutara cuando se presione el boton de
     * regresar.
     */
    public void activateBackArrow(ActionDelegate action) {
        logoBttn.setIcon(backArrow);
        logoBttn.setToolTipText("Regresar");
        backActivate = true;
        backAction.push(action);
    }

    /**
     * Desactiva el boton de regresar asi como todas las acciones que hallan.
     */
    public void deactivateBackArrow() {
        logoBttn.setIcon(logo);
        logoBttn.setToolTipText("REAT");
        backActivate = false;
        backAction.clear();
    }

    /**
     * Ejecuta la ultima accion
     */
    public void executeBackAction() {
        if (backActivate && !backAction.isEmpty()) {
            backAction.pop().doSomething();
            if (backAction.isEmpty()) {
                deactivateBackArrow();
            }
        }else{
            clearIndicators();
            activeSection = -1;
            LayoutUtils.setPanelInto(cover, new About());
        }
    }

    public int activeSection;

    public static final int HOME_SECTION = 1;
    public static final int NEW_SECTION = 2;
    public static final int SAVE_SECTION = 3;
    public static final int WORKSPACE_SECTION = 4;
    public static final int SETTINGS_SECTION = 5;
    public static final int HELP_SECTION = 6;
    public static final int GITHUB_SECTION = 7;
    public static final int FACEBOOK_SECTION = 8;
    public static final int TWITTER_SECTION = 9;
    public static final int GOOGLE_SECTION = 10;

    //GETTERS AND SETTERS
    public JLabel getHomeBttn() {
        return homeBttn;
    }

    public JLabel getHomeIndicator() {
        return homeIndicator;
    }

    public JLabel getNewBttn() {
        return newBttn;
    }

    public JLabel getNewIndicator() {
        return newIndicator;
    }

    public JLabel getSaveBttn() {
        return saveBttn;
    }

    public JLabel getSaveIndicator() {
        return saveIndicator;
    }

    public JLabel getWorkspaceBttn() {
        return workspaceBttn;
    }

    public JLabel getWorkspaceIndicator() {
        return workspaceIndicator;
    }

    public JLabel getSettingsBttn() {
        return settingsBttn;
    }

    public JLabel getSettingsIndicator() {
        return settingsIndicator;
    }

    public JLabel getHelpBttn() {
        return helpBttn;
    }

    public JLabel getHelpIndicator() {
        return helpIndicator;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            boolean f = true;
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    f = false;
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            if (f) {
                javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JPanel cover = new javax.swing.JPanel();
    private javax.swing.JPanel full;
    private javax.swing.JLabel helpBttn;
    private javax.swing.JLabel helpIndicator;
    private javax.swing.JLabel homeBttn;
    public final javax.swing.JLabel homeIndicator = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoBttn;
    private javax.swing.JLabel newBttn;
    private javax.swing.JLabel newIndicator;
    private javax.swing.JLabel saveBttn;
    private javax.swing.JLabel saveIndicator;
    private javax.swing.JLabel settingsBttn;
    private javax.swing.JLabel settingsIndicator;
    private javax.swing.JPanel title;
    private javax.swing.JPanel toolBarPanel;
    private javax.swing.JLabel workspaceBttn;
    private javax.swing.JLabel workspaceIndicator;
    // End of variables declaration//GEN-END:variables
}
