/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uclv.crash.gui.partials.recognition;

import com.uclv.crash.core.Automata;
import com.uclv.crash.gui.AppStorage;
import com.uclv.crash.gui.partials.WorkEditor;
import com.uclv.crash.gui.partials.afdstep.Step;
import com.uclv.crash.gui.utils.LayoutUtils;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Yasiel Cabrera
 */
public class RecognitionDone extends javax.swing.JPanel {

    /**
     * Ultima cadena reconocida
     */
    public static String lastStr;
    /**
     * lista de pasos de la ultima corrida del algoritmo que reconocio la ultima
     * cadena
     */
    public static List<Step> recognition;

    /**
     * Creates new form RecognitionDone
     *
     * @param str
     */
    public RecognitionDone(String str) {
        initComponents();
        RecognitionDone.lastStr = str;

        cadTf.setText(str);

        if (AppStorage.getRegularExpresion() != null) {
            String s = "", re = AppStorage.getRegularExpresion();
            for (int i = 0; i < re.length(); i++) {
                char a = re.charAt(i);
                switch (a) {
                    case '?':
                        s += "\\?";
                        break;
                    case '\\':
                        if (re.charAt(i + 1) == '\\') {
                            s += "\\\\";
                            i++;
                        } else if (re.charAt(i + 1) == '|') {
                            s += "\\|";
                            i++;
                        } else if (re.charAt(i + 1) == '*') {
                            s += "\\*";
                            i++;
                        } else if (re.charAt(i + 1) == '+') {
                            s += "\\+";
                            i++;
                        } else if (re.charAt(i + 1) == '.') {
                            s += "\\.";
                            i++;
                        } else {
                            s += "\\\\";
                        }
                        break;

                    case '.':
                        break;
                    default:
                        s += a;
                }
            }

            jLabel1.setText("La cadena" + (str.matches(s) ? "" : " NO") + " machea. ¿Desea ver el reconocimiento paso a paso?");
        }else{
            Automata t;
            if(AppStorage.getAfnd() != null){
                t = AppStorage.getAfnd();
                jLabel1.setText("La cadena" + (t.recognizeAFND(str, new ArrayList<Step>())? "" : " NO") + " machea. ¿Desea ver el reconocimiento paso a paso?");
            }else{
                t = AppStorage.getAfd();
                jLabel1.setText("La cadena" + (t.recognizeAFD(str, new ArrayList<Step>())? "" : " NO") + " machea. ¿Desea ver el reconocimiento paso a paso?");
            }
            
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        afndBttn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        afdBttn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        afdminBttn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cadTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 42, 113));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("La cadena [no] machea");

        jPanel1.setBackground(new java.awt.Color(0, 42, 113));

        afndBttn.setBackground(new java.awt.Color(0, 30, 84));
        afndBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afndBttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                afndBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                afndBttnMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AFND");

        javax.swing.GroupLayout afndBttnLayout = new javax.swing.GroupLayout(afndBttn);
        afndBttn.setLayout(afndBttnLayout);
        afndBttnLayout.setHorizontalGroup(
            afndBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afndBttnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        afndBttnLayout.setVerticalGroup(
            afndBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afndBttnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(10, 10, 10))
        );

        afdBttn.setBackground(new java.awt.Color(0, 30, 84));
        afdBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afdBttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                afdBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                afdBttnMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("AFD");

        javax.swing.GroupLayout afdBttnLayout = new javax.swing.GroupLayout(afdBttn);
        afdBttn.setLayout(afdBttnLayout);
        afdBttnLayout.setHorizontalGroup(
            afdBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afdBttnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        afdBttnLayout.setVerticalGroup(
            afdBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afdBttnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(10, 10, 10))
        );

        afdminBttn.setBackground(new java.awt.Color(0, 30, 84));
        afdminBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afdminBttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                afdminBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                afdminBttnMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AFD MIN");

        javax.swing.GroupLayout afdminBttnLayout = new javax.swing.GroupLayout(afdminBttn);
        afdminBttn.setLayout(afdminBttnLayout);
        afdminBttnLayout.setHorizontalGroup(
            afdminBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afdminBttnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        afdminBttnLayout.setVerticalGroup(
            afdminBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afdminBttnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(10, 10, 10))
        );

        cadTf.setEditable(false);
        cadTf.setBackground(new java.awt.Color(0, 42, 113));
        cadTf.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cadTf.setForeground(new java.awt.Color(255, 255, 255));
        cadTf.setText("La cadena va aqui...");
        cadTf.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cadena reconocida:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 100, Short.MAX_VALUE)
                        .addComponent(afndBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(afdBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(afdminBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadTf)))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(afdminBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(afdBttn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(afndBttn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void afndBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afndBttnMouseEntered
        afndBttn.setBackground(new Color(0, 34, 96));
    }//GEN-LAST:event_afndBttnMouseEntered

    private void afndBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afndBttnMouseExited
        afndBttn.setBackground(new Color(0, 30, 84));
    }//GEN-LAST:event_afndBttnMouseExited

    private void afdBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afdBttnMouseEntered
        afdBttn.setBackground(new Color(0, 34, 96));
    }//GEN-LAST:event_afdBttnMouseEntered

    private void afdBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afdBttnMouseExited
        afdBttn.setBackground(new Color(0, 30, 84));
    }//GEN-LAST:event_afdBttnMouseExited

    private void afdminBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afdminBttnMouseEntered
        afdminBttn.setBackground(new Color(0, 34, 96));
    }//GEN-LAST:event_afdminBttnMouseEntered

    private void afdminBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afdminBttnMouseExited
        afdminBttn.setBackground(new Color(0, 30, 84));
    }//GEN-LAST:event_afdminBttnMouseExited

    private void afndBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afndBttnMouseClicked
        if (AppStorage.getAfnd() == null) {
            LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionError("AFND"));
        } else {
            recognition = new ArrayList<>();
            System.out.println(AppStorage.getAfnd().recognizeAFND(lastStr, recognition));

            if (AppStorage.getWORK_EDITOR().activeSection != WorkEditor.AFND_SECTION) {
                //go to an intermediate step for say to the user that he should to active AFND section....
                LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionAdvice("AFND"));
            } else {
                LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionProcess("AFND"));
            }
        }
    }//GEN-LAST:event_afndBttnMouseClicked

    private void afdBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afdBttnMouseClicked
        if (AppStorage.getAfd() == null) {
            LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionError("AFD"));
        } else {
            recognition = new ArrayList<>();
            System.out.println(AppStorage.getAfd().recognizeAFD(lastStr, recognition));

            if (AppStorage.getWORK_EDITOR().activeSection != WorkEditor.AFD_SECTION) {
                //go to an intermediate step for say to the user that he should to active AFND section....
                LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionAdvice("AFD"));
            } else {
                LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionProcess("AFD"));
            }
        }
    }//GEN-LAST:event_afdBttnMouseClicked

    private void afdminBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afdminBttnMouseClicked
        if (AppStorage.getAfdmin() == null) {
            LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionError("AFD Mínimo"));
        } else {
            recognition = new ArrayList<>();
            System.out.println(AppStorage.getAfdmin().recognizeAFD(lastStr, recognition));

            if (AppStorage.getWORK_EDITOR().activeSection != WorkEditor.AFDM_SECTION) {
                //go to an intermediate step for say to the user that he should to active AFND section....
                LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionAdvice("AFDM"));
            } else {
                LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionProcess("AFDM"));
            }

            System.out.println(AppStorage.getAfdmin());
            LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionProcess("AFDM"));
        }
    }//GEN-LAST:event_afdminBttnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel afdBttn;
    private javax.swing.JPanel afdminBttn;
    private javax.swing.JPanel afndBttn;
    private javax.swing.JTextField cadTf;
    private javax.swing.JPanel convert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
