/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uclv.crash.gui.partials.recognition;

import com.uclv.crash.gui.AppStorage;
import com.uclv.crash.gui.utils.LayoutUtils;
import java.awt.Color;

/**
 *
 * @author Yasiel Cabrera
 */
public class RecognitionAdvice extends javax.swing.JPanel {
    private String section;
    /**
     * Creates new form RecognitionAdvice
     * @param section
     */
    public RecognitionAdvice(String section) {
        initComponents();
        this.section = section;
        adviceLb.setText("Recomendamos activar el apartado '"+section+"' para ver mejor el reconocimiento.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adviceLb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        continueBttn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 42, 113));

        adviceLb.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        adviceLb.setForeground(new java.awt.Color(255, 255, 255));
        adviceLb.setText("Recomendamos activar el apartado XXX para ver mejor el reconocimiento.");

        jPanel1.setBackground(new java.awt.Color(0, 42, 113));

        continueBttn.setBackground(new java.awt.Color(0, 30, 84));
        continueBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueBttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                continueBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                continueBttnMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CONTINUAR");

        javax.swing.GroupLayout continueBttnLayout = new javax.swing.GroupLayout(continueBttn);
        continueBttn.setLayout(continueBttnLayout);
        continueBttnLayout.setHorizontalGroup(
            continueBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(continueBttnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        continueBttnLayout.setVerticalGroup(
            continueBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(continueBttnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(continueBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(continueBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adviceLb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(adviceLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void continueBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueBttnMouseClicked
        LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionProcess(section));
    }//GEN-LAST:event_continueBttnMouseClicked

    private void continueBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueBttnMouseEntered
        continueBttn.setBackground(new Color(0, 34, 96));
    }//GEN-LAST:event_continueBttnMouseEntered

    private void continueBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueBttnMouseExited
        continueBttn.setBackground(new Color(0, 30, 84));
    }//GEN-LAST:event_continueBttnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adviceLb;
    private javax.swing.JPanel continueBttn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
