/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uclv.crash.gui.partials.recognition;

import com.uclv.crash.core.RegularExpresionTraductor;
import com.uclv.crash.gui.AppStorage;
import com.uclv.crash.gui.utils.LayoutUtils;
import java.awt.event.KeyEvent;

/**
 *
 * @author Yasiel Cabrera
 */
public class RecognitionStart extends javax.swing.JPanel {

    /**
     * Creates new form RecognitionStart
     */
    public RecognitionStart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        strTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 42, 113));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Escriba el texo que desea reconocer");

        jPanel3.setBackground(new java.awt.Color(0, 42, 113));

        strTf.setBackground(new java.awt.Color(0, 30, 84));
        strTf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        strTf.setForeground(new java.awt.Color(255, 255, 255));
        strTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        strTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 30, 84), 10));
        strTf.setCaretColor(new java.awt.Color(255, 255, 255));
        strTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strTfActionPerformed(evt);
            }
        });
        strTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                strTfKeyTyped(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 30, 84));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Chevron_Right_60px.png"))); // NOI18N
        jLabel2.setToolTipText("Convertir a AFND");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(strTf, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void strTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strTfActionPerformed

    private void strTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_strTfKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            jLabel2MouseClicked(null);
        }
    }//GEN-LAST:event_strTfKeyTyped

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(AppStorage.getAfnd() != null || AppStorage.getAfd() != null || AppStorage.getAfdmin()!= null){
            LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionDone(strTf.getText().trim()));
        }else {
            System.out.println("show panel of error because there is not any re, afd or afnd in te system");
        }
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField strTf;
    // End of variables declaration//GEN-END:variables
}
