/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uclv.crash.gui.partials.recognition;

import com.uclv.crash.gui.AppStorage;
import com.uclv.crash.gui.utils.LayoutUtils;
import java.awt.Color;

/**
 *
 * @author Yasiel Cabrera
 */
public class RecognitionError extends javax.swing.JPanel {

    /**
     * Creates new form RecognitionError
     * @param what
     */
    public RecognitionError(String what) {
        initComponents();
        
        errorLb.setText("Primero debe crear un "+what);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorLb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cancelBttn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        atrasBttn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 42, 113));

        errorLb.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        errorLb.setForeground(new java.awt.Color(255, 255, 255));
        errorLb.setText("Primero debe crear un");

        jPanel1.setBackground(new java.awt.Color(0, 42, 113));

        cancelBttn.setBackground(new java.awt.Color(0, 30, 84));
        cancelBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBttnMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CANCELAR");

        javax.swing.GroupLayout cancelBttnLayout = new javax.swing.GroupLayout(cancelBttn);
        cancelBttn.setLayout(cancelBttnLayout);
        cancelBttnLayout.setHorizontalGroup(
            cancelBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelBttnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        cancelBttnLayout.setVerticalGroup(
            cancelBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelBttnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(10, 10, 10))
        );

        atrasBttn.setBackground(new java.awt.Color(0, 30, 84));
        atrasBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasBttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasBttnMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ATRAS");

        javax.swing.GroupLayout atrasBttnLayout = new javax.swing.GroupLayout(atrasBttn);
        atrasBttn.setLayout(atrasBttnLayout);
        atrasBttnLayout.setHorizontalGroup(
            atrasBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atrasBttnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        atrasBttnLayout.setVerticalGroup(
            atrasBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atrasBttnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(atrasBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(cancelBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(atrasBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(errorLb)
                .addContainerGap(271, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBttnMouseEntered
        cancelBttn.setBackground(new Color(0, 34, 96));
    }//GEN-LAST:event_cancelBttnMouseEntered

    private void cancelBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBttnMouseExited
        cancelBttn.setBackground(new Color(0, 30, 84));
    }//GEN-LAST:event_cancelBttnMouseExited

    private void atrasBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBttnMouseEntered
        atrasBttn.setBackground(new Color(0, 34, 96));
    }//GEN-LAST:event_atrasBttnMouseEntered

    private void atrasBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBttnMouseExited
        atrasBttn.setBackground(new Color(0, 30, 84));
    }//GEN-LAST:event_atrasBttnMouseExited

    private void cancelBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBttnMouseClicked
        AppStorage.getWORK_EDITOR().toggleRecognitionPanel();
    }//GEN-LAST:event_cancelBttnMouseClicked

    private void atrasBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBttnMouseClicked
        LayoutUtils.setPanelInto(AppStorage.getWORK_EDITOR().getRecognitionPanel(), new RecognitionDone(RecognitionDone.lastStr));
    }//GEN-LAST:event_atrasBttnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atrasBttn;
    private javax.swing.JPanel cancelBttn;
    private javax.swing.JLabel errorLb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
