/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uclv.crash.gui.pnewa;

import com.sun.glass.events.KeyEvent;
import com.uclv.crash.core.SimplifiedTransition;

/**
 *
 * @author Yasiel Cabrera
 */
public class RemoveTransition extends javax.swing.JPanel {
    
    private final NewAutomata REFERENCE;
    /**
     * Creates new form NewTransition
     * @param reference
     */
    public RemoveTransition(NewAutomata reference) {
        REFERENCE = reference;
        initComponents();
        errorLb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        from = new javax.swing.JTextField();
        cancelBttn = new javax.swing.JLabel();
        acceptBttn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        symbol = new javax.swing.JTextField();
        errorLb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 42, 113));
        setPreferredSize(new java.awt.Dimension(300, 350));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ELIMINAR TRANSICION");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Desde");

        from.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        from.setForeground(new java.awt.Color(0, 42, 113));
        from.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        from.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        from.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fromKeyTyped(evt);
            }
        });

        cancelBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Cancel_36px.png"))); // NOI18N
        cancelBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBttnMouseClicked(evt);
            }
        });

        acceptBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Ok_36px.png"))); // NOI18N
        acceptBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acceptBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptBttnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hasta");

        to.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        to.setForeground(new java.awt.Color(0, 42, 113));
        to.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        to.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        to.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                toKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Símbolo");

        symbol.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        symbol.setForeground(new java.awt.Color(0, 42, 113));
        symbol.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        symbol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        symbol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                symbolKeyTyped(evt);
            }
        });

        errorLb.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        errorLb.setForeground(new java.awt.Color(255, 0, 51));
        errorLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLb.setText("Hay algun error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(from)
                                    .addComponent(to)
                                    .addComponent(symbol))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelBttn)
                        .addGap(18, 18, 18)
                        .addComponent(acceptBttn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(from)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(symbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelBttn)
                    .addComponent(acceptBttn))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fromKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            acceptBttnMouseClicked(null);
        }
        if(from.getText().length() == 3 || !Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_fromKeyTyped

    private void cancelBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBttnMouseClicked
        REFERENCE.changeCover(new Init(REFERENCE));
    }//GEN-LAST:event_cancelBttnMouseClicked

    private void acceptBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptBttnMouseClicked
        if(from.getText().trim().equals("")){
            errorLb.setText("Especifique de que estado parte");
            errorLb.setVisible(true);
            return;
        }
        if(to.getText().trim().equals("")){
            errorLb.setText("Especifique a que estado llega");
            errorLb.setVisible(true);
            return;
        }
        
        int idfrom = Integer.parseInt(from.getText());
        int idto = Integer.parseInt(to.getText());
        char input = symbol.getText().length() == 0? SimplifiedTransition.EMPTY_INPUT : symbol.getText().charAt(0);
        if(REFERENCE.removeTransition(idfrom, idto, input)){
            REFERENCE.changeCover(new Init(REFERENCE));
        }else{
            errorLb.setText("No existe tal transición");
            errorLb.setVisible(true);
        }
    }//GEN-LAST:event_acceptBttnMouseClicked

    private void toKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            acceptBttnMouseClicked(null);
        }
        if(to.getText().length() == 3 || !Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_toKeyTyped

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void symbolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_symbolKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            acceptBttnMouseClicked(null);
        }
        if(symbol.getText().length() == 1){
            evt.consume();
        }
    }//GEN-LAST:event_symbolKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acceptBttn;
    private javax.swing.JLabel cancelBttn;
    private javax.swing.JLabel errorLb;
    private javax.swing.JTextField from;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField symbol;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
