/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uclv.crash.gui.partials;

import com.uclv.crash.gui.App;
import com.uclv.crash.gui.AppStorage;
import com.uclv.crash.gui.Settings;
import java.awt.Color;

/**
 *
 * @author Yasiel Cabrera
 */
public class SettingsOp extends javax.swing.JPanel {

    /**
     * Creates new form Settings
     */
    public SettingsOp() {
        initComponents();
        
        widthTf.setText(AppStorage.getSettings().getWindowsWidth()+"");
        heightTf.setText(AppStorage.getSettings().getWindowsHeight()+"");
        
        msgLb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        banner = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        widthTf = new javax.swing.JTextField();
        heightTf = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        saveBttn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        applyBttn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        msgLb = new javax.swing.JLabel();
        fullScreen = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 30, 84));

        banner.setBackground(new java.awt.Color(227, 239, 239));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Configuración");

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addContainerGap(545, Short.MAX_VALUE))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addGap(10, 10, 10))
        );

        jPanel1.setBackground(new java.awt.Color(0, 42, 113));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tamaño de la ventana");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("pixeles");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("x");

        widthTf.setBackground(new java.awt.Color(0, 30, 84));
        widthTf.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        widthTf.setForeground(new java.awt.Color(255, 255, 255));
        widthTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        widthTf.setText(" ");
        widthTf.setBorder(null);
        widthTf.setCaretColor(new java.awt.Color(255, 255, 255));
        widthTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                widthTfKeyTyped(evt);
            }
        });

        heightTf.setBackground(new java.awt.Color(0, 30, 84));
        heightTf.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        heightTf.setForeground(new java.awt.Color(255, 255, 255));
        heightTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        heightTf.setText(" ");
        heightTf.setBorder(null);
        heightTf.setCaretColor(new java.awt.Color(255, 255, 255));
        heightTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                heightTfKeyTyped(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 42, 113));

        saveBttn.setBackground(new java.awt.Color(0, 30, 84));
        saveBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveBttnMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("GUARDAR");

        javax.swing.GroupLayout saveBttnLayout = new javax.swing.GroupLayout(saveBttn);
        saveBttn.setLayout(saveBttnLayout);
        saveBttnLayout.setHorizontalGroup(
            saveBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveBttnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        saveBttnLayout.setVerticalGroup(
            saveBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveBttnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addGap(10, 10, 10))
        );

        applyBttn.setBackground(new java.awt.Color(0, 30, 84));
        applyBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applyBttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                applyBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                applyBttnMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("APLICAR");

        javax.swing.GroupLayout applyBttnLayout = new javax.swing.GroupLayout(applyBttn);
        applyBttn.setLayout(applyBttnLayout);
        applyBttnLayout.setHorizontalGroup(
            applyBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applyBttnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        applyBttnLayout.setVerticalGroup(
            applyBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applyBttnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(applyBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(saveBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        msgLb.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        msgLb.setForeground(new java.awt.Color(255, 255, 255));
        msgLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgLb.setText("Configuración guardada satisfactoriamente.");

        fullScreen.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        fullScreen.setForeground(new java.awt.Color(255, 255, 255));
        fullScreen.setText("Pantalla completa");
        fullScreen.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(msgLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullScreen)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(widthTf, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10)
                                .addComponent(heightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(widthTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(fullScreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(msgLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBttnMouseClicked
        msgLb.setVisible(true);
        if(build().save()){
            msgLb.setText("Configuración guardada satisfactoriamente.");
        }else{
            msgLb.setText("No se pudo guardar la configuración.");
        }
    }//GEN-LAST:event_saveBttnMouseClicked

    private void saveBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBttnMouseEntered
        saveBttn.setBackground(new Color(0, 34, 96));
    }//GEN-LAST:event_saveBttnMouseEntered

    private void saveBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBttnMouseExited
        saveBttn.setBackground(new Color(0, 30, 84));
    }//GEN-LAST:event_saveBttnMouseExited

    private void applyBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyBttnMouseClicked
        AppStorage.setSettings(build());
        AppStorage.getSettings().apply();
        msgLb.setVisible(true);
        msgLb.setText("Configuración aplicada satisfactoriamente.");
    }//GEN-LAST:event_applyBttnMouseClicked

    private void applyBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyBttnMouseEntered
         applyBttn.setBackground(new Color(0, 34, 96));
    }//GEN-LAST:event_applyBttnMouseEntered

    private void applyBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyBttnMouseExited
         applyBttn.setBackground(new Color(0, 30, 84));
    }//GEN-LAST:event_applyBttnMouseExited

    private void widthTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_widthTfKeyTyped
        if(evt.getKeyChar() < '0' || evt.getKeyChar() > '9'){
            evt.consume();
        }
    }//GEN-LAST:event_widthTfKeyTyped

    private void heightTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heightTfKeyTyped
        if(evt.getKeyChar() < '0' || evt.getKeyChar() > '9'){
            evt.consume();
        }
    }//GEN-LAST:event_heightTfKeyTyped

    private Settings build(){
        Settings x = new Settings();
        x.setWindowsWidth(Integer.parseInt(widthTf.getText()));
        x.setWindowsHeight(Integer.parseInt(heightTf.getText()));
        x.setIsWindowsMaximized(fullScreen.isSelected());
        return x;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel applyBttn;
    private javax.swing.JPanel banner;
    private javax.swing.JCheckBox fullScreen;
    private javax.swing.JTextField heightTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel msgLb;
    private javax.swing.JPanel saveBttn;
    private javax.swing.JTextField widthTf;
    // End of variables declaration//GEN-END:variables
}
