/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uclv.crash.gui.partials.afdminstep;

import com.uclv.crash.core.Group;
import com.uclv.crash.core.Group.Entry;
import com.uclv.crash.gui.partials.afdstep.Step;
import java.util.List;

/**
 *
 * @author Yasiel Cabrera
 */
public class Step3 extends javax.swing.JPanel {
    private final Step step;

    /**
     * Creates new form Step1
     * @param step
     */
    public Step3(Step step) {
        initComponents();
        this.step = step;
        
        List<Group> k0 = (List<Group>) step.getData()[0];
        List<Group> kplus = (List<Group>) step.getData()[1];
        List<Character> alphabet = (List<Character>) step.getData()[2];
        
        k0Ta.setText(getStr(k0, alphabet));
        kplusTa.setText(getStr(kplus, alphabet));
    }
    
    private String getStr(List<Group> list, List<Character> alphabet){
        String answ = "";
        for (int i = 0; i < list.size(); i++) {
            answ += "Grupo "+ (i+1) +"\n";
            answ += "\t";
            for (int j = 0; j < alphabet.size(); j++) {
                answ += alphabet.get(j)+"\t";                
            }
            answ += "\n";
            for(Entry e : list.get(i).entrys){
                answ += e.state.getId()+"\t";
                for(int d : e.list){
                    answ += (d+1)+"\t";
                }
                answ += "\n";
            }
            
            answ += "\n";
        }
        return answ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        k0Ta = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        kplusTa = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 42, 113));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>Obtener P<sub>k</sub> a partir de P<sub>k-1</sub></html>");

        jScrollPane3.setBorder(null);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 42, 113));
        jTextArea2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setTabSize(4);
        jTextArea2.setText("Para cada grupo G de Pk-1, se particiona G en subgrupos de forma que dos estados S y T de G esten en un mismo subgrupo si para todo simbolo a δ(S,a) y δ(T,a) son estados de un mismo grupo de Pk-1. Finalmente Pk son todos los subgrupos formados.");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea2);

        jScrollPane4.setBorder(null);

        k0Ta.setEditable(false);
        k0Ta.setBackground(new java.awt.Color(0, 42, 113));
        k0Ta.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        k0Ta.setForeground(new java.awt.Color(255, 255, 255));
        k0Ta.setLineWrap(true);
        k0Ta.setTabSize(4);
        k0Ta.setText("asdasd");
        k0Ta.setWrapStyleWord(true);
        jScrollPane4.setViewportView(k0Ta);

        jScrollPane5.setBorder(null);

        kplusTa.setEditable(false);
        kplusTa.setBackground(new java.awt.Color(0, 42, 113));
        kplusTa.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        kplusTa.setForeground(new java.awt.Color(255, 255, 255));
        kplusTa.setLineWrap(true);
        kplusTa.setTabSize(4);
        kplusTa.setText("asdasd");
        kplusTa.setWrapStyleWord(true);
        jScrollPane5.setViewportView(kplusTa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea k0Ta;
    private javax.swing.JTextArea kplusTa;
    // End of variables declaration//GEN-END:variables
}
