/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uclv.crash.gui.partials.afdstep;

import javax.swing.ImageIcon;

/**
 *
 * @author Yasiel Cabrera
 */
public class AFDAlgorithm extends javax.swing.JPanel {

    /**
     * Creates new form Algorithm
     */
    public AFDAlgorithm() {
        initComponents();
    }
    
    private final ImageIcon arrow = new ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Play_20px.png"));
    private int last = -1;
    /**
     * Marca el paso actual del algoritmo que se esta ejecutando
     * @param x Paso del algoritmo a ejecutar
     */
    public void activeStep(int x){
        if(last != -1){
            deactivate(last);
        }
        switch(x){
            case 1:
                p1.setText("");
                p1.setIcon(arrow);
                break;
            case 2:
                p2.setText("");
                p2.setIcon(arrow);
                break;
            case 3:
                p3.setText("");
                p3.setIcon(arrow);
                break;
            case 4:
                p4.setText("");
                p4.setIcon(arrow);
                break;
            case 5:
                p5.setText("");
                p5.setIcon(arrow);
                break;
            case 6:
                p6.setText("");
                p6.setIcon(arrow);
                break;
            case 7:
                p7.setText("");
                p7.setIcon(arrow);
                break;
            case 8:
                p8.setText("");
                p8.setIcon(arrow);
                break;
            case 9:
                p9.setText("");
                p9.setIcon(arrow);
                break;
            case 10:
                p10.setText("");
                p10.setIcon(arrow);
                break;
            case 11:
                p11.setText("");
                p11.setIcon(arrow);
                break;
            case 12:
                p12.setText("");
                p12.setIcon(arrow);
                break;                
        }
        last = x;
    }
    
    private void deactivate(int x){
        switch(x){
            case 1:
                p1.setText(x+"");
                p1.setIcon(null);
                break;
            case 2:
                p2.setText(x+"");
                p2.setIcon(null);
                break;
            case 3:
                p3.setText(x+"");
                p3.setIcon(null);
                break;
            case 4:
                p4.setText(x+"");
                p4.setIcon(null);
                break;
            case 5:
                p5.setText(x+"");
                p5.setIcon(null);
                break;
            case 6:
                p6.setText(x+"");
                p6.setIcon(null);
                break;
            case 7:
                p7.setText(x+"");
                p7.setIcon(null);
                break;
            case 8:
                p8.setText(x+"");
                p8.setIcon(null);
                break;
            case 9:
                p9.setText(x+"");
                p9.setIcon(null);
                break;
            case 10:
                p10.setText(x+"");
                p10.setIcon(null);
                break;
            case 11:
                p11.setText(x+"");
                p11.setIcon(null);
                break;
            case 12:
                p12.setText(x+"");
                p12.setIcon(null);
                break;              
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        p9 = new javax.swing.JLabel();
        p10 = new javax.swing.JLabel();
        p11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        p12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 42, 113));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Algoritmo");

        p1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 255, 255));
        p1.setText("1");

        p2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 255, 255));
        p2.setText("2");

        p3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        p3.setForeground(new java.awt.Color(255, 255, 255));
        p3.setText("3");

        p4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        p4.setForeground(new java.awt.Color(255, 255, 255));
        p4.setText("4");

        p5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        p5.setForeground(new java.awt.Color(255, 255, 255));
        p5.setText("5");

        p6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        p6.setForeground(new java.awt.Color(255, 255, 255));
        p6.setText("6");

        p7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        p7.setForeground(new java.awt.Color(255, 255, 255));
        p7.setText("7");

        p8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        p8.setForeground(new java.awt.Color(255, 255, 255));
        p8.setText("8");

        p9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        p9.setForeground(new java.awt.Color(255, 255, 255));
        p9.setText("9");

        p10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        p10.setForeground(new java.awt.Color(255, 255, 255));
        p10.setText("10");

        p11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        p11.setForeground(new java.awt.Color(255, 255, 255));
        p11.setText("11");

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("S'o = e-clausura( {So} )");

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("S' = {S'o} ");

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Indicar que So' está NO MARCADO (!M)");

        p12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        p12.setForeground(new java.awt.Color(255, 255, 255));
        p12.setText("12");

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mientras Ǝ T ϵ S' !M");

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Marcar T");

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Paca cada a ϵ Σ ");

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("A = mover(T,a)");

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("U = e-clausura(A)");

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("si U no ϵ S'");

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("añadir U a S' como !M");

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("δ'(T,a) = U");

        jLabel26.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("F' = todos T ϵ S' / Ǝ(x ϵ F) c T");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p3)
                                    .addComponent(p4)
                                    .addComponent(p12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(p10)
                                        .addGap(111, 111, 111)
                                        .addComponent(jLabel24))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(p2)
                                            .addComponent(p1))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(p5)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(p7)
                                            .addComponent(p8)
                                            .addComponent(p9)
                                            .addComponent(p11))
                                        .addGap(77, 77, 77)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel21))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p6)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p6)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p7)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p8)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p9)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p10)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p11)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p12)
                    .addComponent(jLabel26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p10;
    private javax.swing.JLabel p11;
    private javax.swing.JLabel p12;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel p9;
    // End of variables declaration//GEN-END:variables
}
