/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uclv.crash.gui.partials.afdstep;

import com.uclv.crash.core.State;
import com.uclv.crash.gui.AppStorage;
import com.uclv.crash.gui.utils.LayoutUtils;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Yasiel Cabrera
 */
public class AFDStep extends javax.swing.JPanel {

    private final AFDAlgorithm algorithm = new AFDAlgorithm();
    private List<Step> steps;
    private int currentStep = 0;

    /**
     * Creates new form AFDStep
     */
    public AFDStep(List<Step> list) {
        initComponents();
        this.steps = list;
        asideCover.setVisible(false);
        LayoutUtils.setPanelInto(asideCover, algorithm);

        stepCount.setText(1 + " / " + steps.size());
        algorithm.activeStep(1);
        LayoutUtils.setPanelInto(stepArea, new Step1(steps.get(currentStep)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asideCover = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stepCount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stepArea = new javax.swing.JPanel();
        verAnswerBttn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 42, 113));

        javax.swing.GroupLayout asideCoverLayout = new javax.swing.GroupLayout(asideCover);
        asideCover.setLayout(asideCoverLayout);
        asideCoverLayout.setHorizontalGroup(
            asideCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        asideCoverLayout.setVerticalGroup(
            asideCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 42, 113));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Chevron_Left_25px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stepCount.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        stepCount.setForeground(new java.awt.Color(255, 255, 255));
        stepCount.setText("1 / 20");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Back_To_30px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Next_page_30px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout stepAreaLayout = new javax.swing.GroupLayout(stepArea);
        stepArea.setLayout(stepAreaLayout);
        stepAreaLayout.setHorizontalGroup(
            stepAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        stepAreaLayout.setVerticalGroup(
            stepAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        verAnswerBttn.setBackground(new java.awt.Color(0, 30, 84));
        verAnswerBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verAnswerBttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verAnswerBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verAnswerBttnMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VER RESULTADO");

        javax.swing.GroupLayout verAnswerBttnLayout = new javax.swing.GroupLayout(verAnswerBttn);
        verAnswerBttn.setLayout(verAnswerBttnLayout);
        verAnswerBttnLayout.setHorizontalGroup(
            verAnswerBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verAnswerBttnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );
        verAnswerBttnLayout.setVerticalGroup(
            verAnswerBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verAnswerBttnLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stepCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                        .addComponent(verAnswerBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stepArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(asideCover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asideCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(stepArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(stepCount)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(verAnswerBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        if (asideCover.isVisible()) {
            jLabel1.setIcon(c_left);
            asideCover.setVisible(false);
        } else {
            jLabel1.setIcon(c_right);
            asideCover.setVisible(true);
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if (currentStep != steps.size() - 1) {
            stepCount.setText((++currentStep + 1) + " / " + steps.size());
            algorithm.activeStep(steps.get(currentStep).getStepNumber());
            showStep(currentStep);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if(currentStep != 0){
            stepCount.setText((--currentStep + 1) + " / " + steps.size());
            algorithm.activeStep(steps.get(currentStep).getStepNumber());
            showStep(currentStep);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void verAnswerBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verAnswerBttnMouseEntered
        verAnswerBttn.setBackground(new Color(0, 34, 96));
    }//GEN-LAST:event_verAnswerBttnMouseEntered

    private void verAnswerBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verAnswerBttnMouseExited
        verAnswerBttn.setBackground(new Color(0, 30, 84));
    }//GEN-LAST:event_verAnswerBttnMouseExited

    private void verAnswerBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verAnswerBttnMouseClicked
        AppStorage.getAFD().remember();
    }//GEN-LAST:event_verAnswerBttnMouseClicked

    private void showStep(int step){
        switch(steps.get(currentStep).getStepNumber()){
            case 1:
                LayoutUtils.setPanelInto(stepArea, new Step1(steps.get(currentStep)));
                break;
            case 2:
                LayoutUtils.setPanelInto(stepArea, new Step2(steps.get(currentStep)));
                break;
            case 3:
                LayoutUtils.setPanelInto(stepArea, new Step3(steps.get(currentStep)));
                break;
            case 4:
                LayoutUtils.setPanelInto(stepArea, new Step4(steps.get(currentStep)));
                break;
            case 5:
                LayoutUtils.setPanelInto(stepArea, new Step5(steps.get(currentStep)));
                break;
            case 6:
                LayoutUtils.setPanelInto(stepArea, new Step6(steps.get(currentStep)));
                break;
            case 7:
                LayoutUtils.setPanelInto(stepArea, new Step7(steps.get(currentStep)));
                break;
            case 8:
                LayoutUtils.setPanelInto(stepArea, new Step8(steps.get(currentStep)));
                break;
            case 9:
                LayoutUtils.setPanelInto(stepArea, new Step9(steps.get(currentStep)));
                break;
            case 10:
                LayoutUtils.setPanelInto(stepArea, new Step10(steps.get(currentStep)));
                break;
            case 11:
                LayoutUtils.setPanelInto(stepArea, new Step11(steps.get(currentStep)));
                break;
            case 12:
                LayoutUtils.setPanelInto(stepArea, new Step12(steps.get(currentStep)));
                break;
        }
    }
    
    private ImageIcon c_right = new ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Chevron_Right_25px.png"));
    private ImageIcon c_left = new ImageIcon(getClass().getResource("/com/uclv/crash/gui/img/icons8_Chevron_Left_25px.png"));
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel asideCover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel stepArea;
    private javax.swing.JLabel stepCount;
    private javax.swing.JPanel verAnswerBttn;
    // End of variables declaration//GEN-END:variables
    public static String toComma(List<State> l) {
        String ans = "";
        for (int j = 0; j < l.size(); j++) {
            ans += l.get(j).getId() + (j == l.size() - 1 ? "" : ",");
        }
        return ans;
    }
    
}
